title:        WSG Status
tagline:      ''
description:  'Overview of all WSG projects'
url:          
version:      1.1.1
author:
  name:       'xTuple'
  email:      'jfischer@xtuple.com'
markdown:     rdiscount
permalink:    pretty
pygments:     true
paginate:     5
